# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_divide_by_rowsum <- function(X) {
    .Call(`_BayesClassifiers_rcpp_divide_by_rowsum`, X)
}

rcpp_rowProd <- function(X, prior) {
    .Call(`_BayesClassifiers_rcpp_rowProd`, X, prior)
}

